# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RUfPDcY9rXnDRZzj5aaoYvLkEGFVO3TH
"""

import plotly.express as px
import plotly.graph_objects as go
import yfinance as yf
import pandas as pd
import numpy as np
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns

st.set_page_config(layout="wide")

st.title("📊 Growth Stock Screener Dashboard")
st.markdown("Analyze growth, quality, momentum, and valuation metrics across your custom watchlist.")

# Define watchlist
# Sidebar input
st.sidebar.header("⚙️ Stock Selection")
tickers_input = st.sidebar.text_input(
    "Enter tickers (comma-separated)", 
    value="AXON, CELH, DUOL, INTA, IOT, APP, ENPH, ON, DT, GLOB, ADYEN"
)

# Convert user input into a list
watchlist = [ticker.strip().upper() for ticker in tickers_input.split(",") if ticker.strip()]


price_data = {}
results = []

with st.spinner("Fetching data..."):
    for ticker in watchlist:
        try:
            stock = yf.Ticker(ticker)
            info = stock.info
            history = stock.history(period="6mo", interval="1d")

            # RSI calculation
            delta = history['Close'].diff()
            gain = delta.clip(lower=0).rolling(window=14).mean()
            loss = -delta.clip(upper=0).rolling(window=14).mean()
            RS = gain / loss
            RSI = 100 - (100 / (1 + RS))
            latest_rsi = RSI.iloc[-1] if not RSI.empty else None

            # Metrics with clipping
            pe = info.get("trailingPE", None)
            if pe is not None:
                pe = min(pe, 100)
            eps_growth = max(min(info.get("earningsQuarterlyGrowth", 0), 2), -1)
            rev_growth = max(min(info.get("revenueGrowth", 0), 2), -1)
            roe = max(min(info.get("returnOnEquity", 0), 2), -1)
            perf_12m = max(min(info.get("52WeekChange", 0), 2), -1)

            # PEG calculation
            peg = (pe / (rev_growth * 100)) if pe and rev_growth else None

            # ROIC calculation
            bs = stock.balance_sheet
            is_ = stock.financials
            try:
                EBIT = is_.loc["EBIT"].iloc[0] if "EBIT" in is_.index else None
                TotalDebt = bs.loc["Long Term Debt"].iloc[0] + bs.loc["Short Long Term Debt"].iloc[0] if "Long Term Debt" in bs.index and "Short Long Term Debt" in bs.index else None
                TotalEquity = bs.loc["Total Stockholder Equity"].iloc[0] if "Total Stockholder Equity" in bs.index else None
                Cash = bs.loc["Cash"] if "Cash" in bs.index else 0
                TaxRate = 0.21
                if EBIT and TotalDebt and TotalEquity:
                    NOPAT = EBIT * (1 - TaxRate)
                    IC = TotalDebt + TotalEquity - Cash.iloc[0] if not isinstance(Cash, (int, float)) else TotalDebt + TotalEquity - Cash
                    roic = NOPAT / IC if IC != 0 else None
                else:
                    roic = None
            except:
                roic = None

            roic = max(min(roic or 0, 2), -1)

            # Scores
            growth_score = np.mean([rev_growth, eps_growth])
            quality_score = np.mean([roe, roic])
            momentum_score = perf_12m
            valuation_score = -pe if pe else 0

            raw_score = (
                0.4 * growth_score +
                0.2 * momentum_score +
                0.2 * quality_score +
                0.2 * valuation_score
            )

            investment_score = max(1, min(10, ((raw_score + 1) * 5)))

            results.append({
                "Ticker": ticker,
                "Company": info.get("shortName", ""),
                "Industry": info.get("industry", ""),
                "PE": pe,
                "PEG": round(peg, 2) if peg else None,
                "Rev Growth": rev_growth,
                "EPS Growth": eps_growth,
                "ROE": roe,
                "ROIC": round(roic, 4) if roic else None,
                "RSI": round(latest_rsi, 2) if latest_rsi else None,
                "12M Perf": perf_12m,
                "Investment Score (1–10)": round(investment_score, 2)
            })

            hist_5y = stock.history(period="5y", interval="1d")
            if not hist_5y.empty:
                price_data[ticker] = hist_5y['Close']

        except Exception as e:
            st.warning(f"Error with {ticker}: {e}")

# Display dataframe
df = pd.DataFrame(results).fillna(0)
st.subheader("📋 Screener Table")
st.dataframe(df.set_index("Ticker"))

# Heatmap
st.subheader("🔥 Heatmap of Key Metrics")
fig, ax = plt.subplots(figsize=(10, 6))
sns.heatmap(df.set_index("Ticker")[["Rev Growth", "EPS Growth", "ROE", "ROIC", "RSI", "12M Perf", "Investment Score (1–10)"]], cmap="coolwarm", annot=True, fmt=".2f", ax=ax)
st.pyplot(fig)

# Bar plot of investment scores
st.subheader("🏆 Investment Score by Ticker")
fig2, ax2 = plt.subplots(figsize=(10, 5))
sns.barplot(x="Ticker", y="Investment Score (1–10)", data=df.sort_values("Investment Score (1–10)", ascending=False), palette="viridis", ax=ax2)
ax2.set_ylim(0, 10)
ax2.grid(axis='y')
st.pyplot(fig2)

# Line plot: 5-year price performance
st.subheader("📈 5-Year Price Performance")
fig3, ax3 = plt.subplots(figsize=(12, 6))
for ticker, prices in price_data.items():
    ax3.plot(prices, label=ticker)
ax3.set_title("5-Year Stock Prices")
ax3.set_xlabel("Date")
ax3.set_ylabel("Price (USD)")
ax3.legend()
ax3.grid(True)
st.pyplot(fig3)

#new one here
# Bar plot of investment scores (interactive)
st.subheader("🏆 Investment Score by Ticker")

fig2 = px.bar(
    df.sort_values("Investment Score (1–10)", ascending=False),
    x="Ticker",
    y="Investment Score (1–10)",
    color="Investment Score (1–10)",
    color_continuous_scale="viridis",
    title="Investment Score Ranking",
    labels={"Investment Score (1–10)": "Score"}
)
st.plotly_chart(fig2, use_container_width=True)
